### ISSUE TITLE
Alternative program to NCO

### ISSUE THREAD

**Issue by jvalan** [NCAR/VAPOR-SupportPage#10]
I am trying to combine multiple 3d netcdf files into a single 4d file. I was recommended NCO to do so, but this program isn't working out for me. Does anyone know of any alternatives that can accomplish this?

**Comment by sgpearse** [comment]
It's hard to say without knowing the command you tried.

[This thread](https://stackoverflow.com/questions/23957350/netcdf-time-dimension-missing-cdo) seems to do what you're looking for.  It's a different link than the first one I gave you.  The user 'Ales' has a command that adds a time dimension to a file.  The user 'N1B4' has another command that is similar, but also relevant to what you/re trying to do.

I believe something like this will do the job:

ncecat -u time A.nc B.nc C.nc concatenatedFile.nc

**Comment by sgpearse** [comment]
jvalan, I'm going to close this issue and continue our discussion on your other ticket, #9
