### ISSUE TITLE
Change .vdf file of VAPOR2 to VAPOR 3 format

### ISSUE THREAD

**Issue by wxminjp** [NCAR/VAPOR-SupportPage#11]
Hi.
I have a vdf file of VAPOR2 (that can open using vapor 2.6.0), but not have the raw file.
I try to import a vdf file on VAPOR 3, but can't open that file.
How to change the vdf file to VAPOR 3 format? 
I checked that your document and tutorial page on the website, I can't find that information.
Is it can't open a vdf file on VAPOR 3?

**Comment by sgpearse** [comment]
Hi there.  Vapor2 should have a tool called vdf2raw, which can convert your .vdf file and its contents into raw, binary data.  After doing this, you can run Vapor3's raw2vdc.  Note that there's a difference between Vapor2's data format (vdf) and Vapor3's (vdc).

**Comment by wxminjp** [comment]
thanks. I'll check
