### ISSUE TITLE
how does one create a vdc file from vdf?  links on vapor documentation site are broken

### ISSUE THREAD

**Issue by paul-markowski** [NCAR/VAPOR-SupportPage#12]
I've been a vapor 2.x user and have .vdf datatsets.  In upgrading to vapor 3.x, however, my vdf datasets can no longer be read by vapor.  I see that I now need .vdc files.  However, I cannot figure out how to create .vdc from .vdf.  The links at this URL (https://ncar.github.io/vapor2website/docs/vapor-data-preparation/vapor-data-preparation.html) are all or mostly broken.  

Thanks.

Paul

**Comment by sgpearse** [comment]
Hi Paul, you're actually the second person to ask this question in a week.  I'm going to create a feature request to develop a tool that helps users with this task.  Thank you for asking the question.

In the mean time, you can do the following to get your VDF data into the new VDC format:

> Hi there. Vapor2 should have a tool called vdf2raw, which can convert your .vdf file and its contents into raw, binary data. After doing this, you can run Vapor3's raw2vdc. Note that there's a difference between Vapor2's data format (vdf) and Vapor3's (vdc).

**Comment by paul-markowski** [comment]
Terrific! Thanks!

On Nov 19, 2019, at 10:31 AM, sgpearse <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Paul, you're actually the second person to ask this question in a week. I'm going to create a feature request to develop a tool that helps users with this task. Thank you for asking the question.

In the mean time, you can do the following to get your VDF data into the new VDC format:

Hi there. Vapor2 should have a tool called vdf2raw, which can convert your .vdf file and its contents into raw, binary data. After doing this, you can run Vapor3's raw2vdc. Note that there's a difference between Vapor2's data format (vdf) and Vapor3's (vdc).
