### ISSUE TITLE
'Short read on input file' when using raw2vdc

### ISSUE THREAD

**Issue by Jason19891009** [NCAR/VAPOR-SupportPage#13]
when converting the raw data to vdc using raw2vdc, there's a promt issuing 'Short read on input file'. And the data are not converted into vdc, and the renderer didn't work with that variable. How can i solve this?

**Comment by sgpearse** [comment]
Hi Jason, this error means that the size of the file does not match the description of your data.  Either the grid was not specified with the correct number of points, or you're not specifying the correct floating point precision of your data.

If your raw file stores double floating point values, include the -double flag with vdccreate.  Also make sure that your grid is specified correctly with the -dimension flag.

If this is still not working, you can post a link to one of your files, along with the command you're trying and I can take a look.

**Comment by Jason19891009** [comment]
Thanks for your kindly reply. I tried again following your suggestion, but it still did not work.  The attched files are my command in windows and the data files. Thanks again for your help.
[datafile.zip](https://github.com/NCAR/VAPOR-GitHubPage/files/3872460/datafile.zip)

**Comment by sgpearse** [comment]
Thank you for reporting this.  The file sizes and parameters are all correct and I am indeed seeing this behavior on Windows, but not on OSX.

I'll file a bug report and we'll fix this before our next release.  In the mean time, is there another machine you can run the conversion on, then transfer the converted data to where you need it (your Windows machine)?

If not, I may be able to assist you.  Your converted data should be less than a GB in size if you have 100 timesteps.

**Comment by sgpearse** [comment]
@Jason19891009 Version 3.2 was released this week.  This problem has been fixed.  Please give it a shot!

https://www.docs.vapor.ucar.edu/downloads.html
