### ISSUE TITLE
Renderer will not display anything

### ISSUE THREAD

**Issue by kalundquist** [NCAR/VAPOR-SupportPage#15]
I am running Vapor 3.1.0 on a Mac and I cannot get anything to display in the renderer.  I am loading WRF data, choosing a renderer, and clicking the "enable" check box, but nothing appears.  Am I missing a step?  I noticed there is a bug mentioned with Intel graphics cards, which I have. Thanks for any help.

**Comment by sgpearse** [comment]
Hi, what renderer are you enabling?  Do you see the white bounding box, which defines where your data domain lies?

**Comment by kalundquist** [comment]
I do not see the wire frame for the domain.  I have tried the slice, volume, and contour renderers.  Vapor2 is working for me, but with Vapor3 the visualizer is just black.

**Comment by kalundquist** [comment]
I have the Intel Iris Pro graphics card and I am wondering if that is the problem.

**Comment by sgpearse** [comment]
Intel graphics shouldn't be a problem.  The data could be a problem if it's post-processed, or it's not WRF-ARW.  Do you have a sample file we can look at?

**Comment by kalundquist** [comment]
Sure, I put the file at the link below.  It is a native WRF-ARW file from an idealized simulation.  I haven’t had a problem viewing it with Vapor 2.  Perhaps I am just doing something incorrectly in Vapor 3.
Katie

ftp://ftp.llnl.gov/outgoing/wrfout_d01_2013-01-01_09:30:00

**Comment by sgpearse** [comment]
Thank you for reporting this.  I'm able to reproduce the problem, and I'll file a new bug report.  I expect that this will be fixed in our next release, which I believe will be released early in 2020.

Feel free to follow the bug at the link below:

https://github.com/NCAR/VAPOR/issues/1947

**Comment by kalundquist** [comment]
Thanks for your help.
