### ISSUE TITLE
Unable to open netCDF files

### ISSUE THREAD

**Issue by brigittahollosi** [NCAR/VAPOR-SupportPage#16]
Dear developers, 
I recently created some multi-dimensional CF-netCDF climate model outputs including several variables. As I tried to import these into Vapor, selected any of the possibilities (Volume, Slice etc.) and enabled rendering, the following error message appeared: 

********************************
Vapor 3.1.0.
OS: Windows 6.2 (9200)
-------------------
Paint failed
-------------------
Error performing paint event
Failed to read variable "" at time step (0), and refinement level (-1) and level-of-detail (0)
Invalid variable reference : 
Failed to read variable "" at time step (0), and refinement level (-1) and level-of-detail (0)
Invalid variable reference : 
********************************

I could manage to import the provided test file "[dukuSample](https://dashrepo.ucar.edu/dataset/VAPOR_Sample_Data/file/dukuSample.tar.gz)" and open it without any issues. Therefore, I would kindly ask you to provide me/us a working small netcdf sample file to compare it with my input. Any other suggestion or advice regarding netCDF files would be also appreciated. 

Thank you in advance, Brigitta

**Comment by sgpearse** [comment]
Hi Brigitta,

Here's a sample file: 

https://drive.google.com/open?id=16lObYrVFow_WFq1JpduiTkDPo0HXTR7F

You can also use this file checker to test for CF compliance:

http://cfconventions.org/compliance-checker.html

-Scott

**Comment by brigittahollosi** [comment]
Hi Scott,

thank you for the provided file, in the meantime, I could manage to adapt my netcdf and read the data. 

Best regards, Brigitta
