### ISSUE TITLE
Keyframing Vapor 3.2.0

### ISSUE THREAD

**Issue by Lisbellaw1958** [NCAR/VAPOR-SupportPage#18]
Hi all,
is keyframing for Vapor 3.2.0 activated/available? I tried to use it under windows but it seems to be deactivated. I can not use/enter the panel "Key frame settings" although it is visible to me. Thanks for any help.

Kind regards,
Sebastian

**Comment by sgpearse** [comment]
Hi Sebastian,

We've had this on our minds for a few years.  I'm surprised it's not an enhancement request yet.  I just filed one, but I'm not sure when we will get to it.  You can follow the link below for updates.

https://github.com/NCAR/VAPOR/issues/2230

-Scott
