### ISSUE TITLE
Question about Error Message Log

### ISSUE THREAD

**Issue by jvalan** [NCAR/VAPOR-SupportPage#19]
I received this error log message when paint failed due to a flow renderer not working:

Error performing paint event
Please provide at least 2 field variables for advection!

As far as I know, Flow renderer doesn't play well with other renderers and fails when there is too much on screen. Could someone explain to me why I am receiving this message. What are the field variables it wants? What's the advection it's doing?

**Comment by sgpearse** [comment]
Hi @jvalan, I transferred this question to our support page.  This is where we address non-bug issues.

The Flow renderer needs two or three variables to calculate trajectories.  The calculation of these trajectories is called advection.  If you're getting this error, then you need to select at least one more variable in the Variables tab.  You can advect on the XY, XZ, YZ, or XYZ axes.
