### ISSUE TITLE
Vapor3 Image Capture "Paint Failed" Error

### ISSUE THREAD

**Issue by AustinDixon** [NCAR/VAPOR-SupportPage#20]
I am trying to do an image capture for a sequence of files but I keep getting a "Paint Failed" error each time Vapor3 steps forward through the files. I am running the software on a Mac.

**Comment by sgpearse** [comment]
A few questions: 
1) What version of Vapor are you running?
2) What format is your data in?
3) What graphics card are you using? 
4) Do you have a sample file we can test?

**Comment by AustinDixon** [comment]
Version is 3.1.0

The data format is NetCDF-CF

The graphics card is a NVIDIA GeForce GT 755M 1024 MB, which is old and wimpy and could easily be the problem. I'm upgrading to a new computer with a much better card soon but I wanted to make sure there are no other issues.

I don't have a sample file I can share at this time.

**Comment by sgpearse** [comment]
> Version is 3.1.0

Try 3.2!

https://www.docs.vapor.ucar.edu/downloads.html

**Comment by AustinDixon** [comment]
That fixed it! Thanks!
