### ISSUE TITLE
Display already-computed trajectories or paths?

### ISSUE THREAD

**Issue by SRHelicity** [NCAR/VAPOR-SupportPage#21]
I'm running CM1 and having it compute (online) trajectories. I'm writing a script to convert those NetCDF trajectory files to Cf-compliant files following the examples provided for trajectory files at http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html#trajectory-data . When I get done with this and have a Cf-compliant trajectory file, can I use VAPOR to display the path/trajectories? I know that VAPOR can compute what are essentially time-invariant streamlines and time-variant pathlines/trajectories using the Flow Renderer if provided U/V/W data, but I don't see anything on the VAPOR pages (e.g., https://www.docs.vapor.ucar.edu/index.html) about displaying already-computed paths or trajectories. I don't want to save history files with enough granularity/temporal frequency to get the U/V/W data to use VAPOR's Flow Renderer when I can have the model compute the trajectories online. Thank you!

**Comment by shaomeng** [comment]
Hello @SRHelicity , you're right that currently VAPOR does NOT have the capability of displaying existing trajectories. 

I've put a feature request of a such capability in the developer website: https://github.com/NCAR/VAPOR/issues/2244 . We will assess the priority of this feature, and you're welcome to keep an eye on the development of that feature request.

**Comment by sgpearse** [comment]
Tracking on vapor's developer page.  Closing here.
