### ISSUE TITLE
Help updating cache size and available CPU cores

### ISSUE THREAD

**Issue by AustinDixon** [NCAR/VAPOR-SupportPage#23]
In VAPOR it says to click "make default" after changes have been made under the startup settings tab, but that option is not showing up on my GUI. I only have the ability to restore defaults. Exiting and re-launching VAPOR only resets the defaults. I am running version 3.2.0 on Windows 10 Pro version 1903.

**Comment by AustinDixon** [comment]
Okay apparently hitting Enter after inputting the desired values acts as the "make default" function. Sorry for the trouble!

**Comment by clyne** [comment]
In our attempt to make things simpler we somehow managed to make them more confusing :-)
