### ISSUE TITLE
Creating .vdc files through IDL scripts

### ISSUE THREAD

**Issue by AvijeetPrasad** [NCAR/VAPOR-SupportPage#6]
Hi,
I have been using VAPOR 2 with variables being computed in IDL. I am used to generating the .vdf format files through WriteVDF.pro code. Do we have similar extensions for VAPOR 3?

**Comment by sgpearse** [comment]
Hi Avijeet.  We do not have any utility that does this in Vapor3.  I've actually never used this utility in Vapor2, so I'm not clear on what it does.

Is your data NetCDF or binary?  The data readers in Vapor3 are more general than they were in Vapor2, so there may be an easier way to get your data in.

**Comment by clyne** [comment]
Hi Avijeet, Just to follow up Scott’s comments I’d be curious to hear more about how you are using the IDL API in Vapor2. Though it is unlikely that the NCAR team would add IDL support to VAPOR3 we are making investments in Python.

cheers - jc


> On Sep 12, 2019, at 3:21 PM, sgpearse <notifications@github.com> wrote:
> 
> Hi Avijeet. We do not have any utility that does this in Vapor3. I've actually never used this utility in Vapor2, so I'm not clear on what it does.
> 
> Is your data NetCDF or binary? The data readers in Vapor3 are more general than they were in Vapor2, so there may be an easier way to get your data in.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

John Clyne
National Center for Atmospheric Research
303.497.1236 (w), 303.809.1922 (c)
clyne@ucar.edu

**Comment by AvijeetPrasad** [comment]
Hi Scott and John,

Thanks for your replies. I have been working on extrapolation of coronal magnetic fields: here the input data is the Sun's photospheric vector magnetic field which comes in FITS format. I do all the data processing and computations in IDL using the instrument-specific Solarsoft packages. Typically I'll have the three components of the magnetic field and its derived quantities like current and Lorentz force as output. For visualization, I use the VAPOR-IDL extension following the example given in the file "vapor-2.6.0.RC0/share/examples/idl/WriteVDF.pro". 

If not in IDL, can we expect similar support for python? If so, I would port my scripts to python and continue with the same workflow.

Thanks and regards
Avijeet

**Comment by clyne** [comment]
Hi Avijeet,

Thanks for clarification on the workflow. Yes, we plan to provide Python bindings to the VDC API. However, we don't have a schedule for this yet. In the interim you have a couple of options:

1. Make use of the command line conversion utilities (vdccreate and raw2vdc). I'm sure that you could invoke these directly from IDL.

2. If your data are not too large you, and you don't need to take advantage of the VDC's wavelet encoding, you could simply output CF compliant NetCDF files from IDL. It looks like IDL supports reading and writing of NetCDF.

cheers - jc

**Comment by AvijeetPrasad** [comment]
Hi John,
Thanks for the suggestions. I'll try them out and see.

Regards
Avijeet
