### ISSUE TITLE
Compile problems with CMAKE

### ISSUE THREAD

**Issue by luo981858** [NCAR/VAPOR-SupportPage#7]
I used VS2017 and QT5.0 to compile CMAKE in windows, but this problem has arisen. How can I solve it?

Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
FREETYPE
    linked by target "render" in directory C:/Windows/VAPOR-VAPOR3_1_0/lib/render
FTGL
    linked by target "render" in directory C:/Windows/VAPOR-VAPOR3_1_0/lib/render
GEOTIFF
    linked by target "render" in directory C:/Windows/VAPOR-VAPOR3_1_0/lib/render
GLEW
    linked by target "vapor" in directory C:/Windows/VAPOR-VAPOR3_1_0/apps/vaporgui
    linked by target "render" in directory C:/Windows/VAPOR-VAPOR3_1_0/lib/render
JPEG
    linked by target "render" in directory C:/Windows/VAPOR-VAPOR3_1_0/lib/render
NETCDF
    linked by target "wasp" in directory C:/Windows/VAPOR-VAPOR3_1_0/lib/wasp
PROJ
    linked by target "vdc" in directory C:/Windows/VAPOR-VAPOR3_1_0/lib/vdc
TIFF
    linked by target "render" in directory C:/Windows/VAPOR-VAPOR3_1_0/lib/render
UDUNITS2
    linked by target "vdc" in directory C:/Windows/VAPOR-VAPOR3_1_0/lib/vdc

Configuring incomplete, errors occurred!
See also "D:/CMake/CMakeFiles/CMakeOutput.log".

thanks in advanced

**Comment by sgpearse** [comment]
Hi, we strongly encourage users to install from our precompiled binary distribution, which you can access from the downloads section of our website: https://www.docs.vapor.ucar.edu/downloads.html

That said, if you're in a situation where you need to build from source, we provide instructions at the following link:  https://www.docs.vapor.ucar.edu/downloads.html#building-from-source

The procedure for building on Windows using Visual Studio 14 2015.  We have no current plans to upgrade in the near future.  We also use CMake for Windows, version 3.14 or greater.

We're in the process of rebuilding our third party libraries, which includes Qt 5.12.4.  If it's Qt5 that you need, stay tuned and we'll have a new batch of libraries and instructions that should be easier than our previous version.

**Comment by luo981858** [comment]
OK,thanks in advanced.
This means if I use your&nbsp;precompiled binary distribution and put them in the C:，I don't need to do STEP 3, 4, 5, 6 in https://www.docs.vapor.ucar.edu/downloads.html.&nbsp;
right?






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "sgpearse"<notifications@github.com&gt;; 
发送时间: 2019年9月19日(星期四) 凌晨0:24
收件人: "NCAR/VAPOR-GitHubPage"<VAPOR-GitHubPage@noreply.github.com&gt;; 
抄送: "Ziming Lo"<541939312@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [NCAR/VAPOR-GitHubPage] Compile problems with CMAKE (#7)




Hi, we strongly encourage users to install from our precompiled binary distribution, which you can access from the downloads section of our website: https://www.docs.vapor.ucar.edu/downloads.html
 
That said, if you're in a situation where you need to build from source, we provide instructions at the following link:  https://www.docs.vapor.ucar.edu/downloads.html#building-from-source
 
The procedure for building on Windows using Visual Studio 14 2015.  We have no current plans to upgrade in the near future.  We also use CMake for Windows, version 3.14 or greater.
 
We're in the process of rebuilding our third party libraries, which includes Qt 5.12.4.  If it's Qt5 that you need, stay tuned and we'll have a new batch of libraries and instructions that should be easier than our previous version.

**Comment by luo981858** [comment]
Hi,
Another question，


My NCL is installed on Linux, but my VAPOR is installed on WINDOWS. How can I convert the output of NCL to TIFF for VAPOR?


Regards,
huihong


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"sgpearse"<notifications@github.com&gt;;
发送时间:&nbsp;2019年9月19日(星期四) 凌晨0:24
收件人:&nbsp;"NCAR/VAPOR-GitHubPage"<VAPOR-GitHubPage@noreply.github.com&gt;;
抄送:&nbsp;"Ziming Lo"<541939312@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [NCAR/VAPOR-GitHubPage] Compile problems with CMAKE (#7)




Hi, we strongly encourage users to install from our precompiled binary distribution, which you can access from the downloads section of our website: https://www.docs.vapor.ucar.edu/downloads.html
 
That said, if you're in a situation where you need to build from source, we provide instructions at the following link:  https://www.docs.vapor.ucar.edu/downloads.html#building-from-source
 
The procedure for building on Windows using Visual Studio 14 2015.  We have no current plans to upgrade in the near future.  We also use CMake for Windows, version 3.14 or greater.
 
We're in the process of rebuilding our third party libraries, which includes Qt 5.12.4.  If it's Qt5 that you need, stay tuned and we'll have a new batch of libraries and instructions that should be easier than our previous version.

**Comment by sgpearse** [comment]
1) If you install the precompiled binary, you don't need to do anything other than install the application.  You can pick the directory that you want to install into, so it doesn't have to be C.

Just to be clear, there are two ways to get Vapor onto your computer.  The first is to just use the installer (precompiled binary).  The second is to compile Vapor from its source code, which is significantly more difficult.  The steps you mention regard building it from source, which we do not recommend.

I think our "Download here" button might not stick out enough on the website.  Follow this link to just use the installer:

https://docs.google.com/forms/d/e/1FAIpQLSfl6Hqh8nPWDnFYGkelf_p5UAqP6ikIKvmLhOOT6cYQePwSnA/viewform

2)  Our previous version of Vapor (version 2) came with a script called tiff2geotiff.  If you intall Vapor2, you will get this script.  The link to download Vapor 2 is at the bottom of the Downloads section of our website (link: https://www.docs.vapor.ucar.edu/downloads.html#vapor-2).

You can read more documentation on how to use it at the link below.

http://eams2.usfs.msu.edu/study/info-EAMC-else/info-vapor/WRFsupport.doc
