### ISSUE TITLE
VAssert(dims.size() >= 1 && dims.size() <=2) failed in DataMgr.cpp, line 3575

### ISSUE THREAD

**Issue by manuelvalera** [NCAR/VAPOR-SupportPage#8]
Hi,

I am trying to run in CentOS, the program starts up and opens with the following messages:

```
X Error: BadValue (integer parameter out of range for operation) 2
  Extension:    152 (Uknown extension)
  Minor opcode: 3 (Unknown request)
  Resource id:  0x0
X Error: BadValue (integer parameter out of range for operation) 2
  Extension:    152 (Uknown extension)
  Minor opcode: 3 (Unknown request)
  Resource id:  0x0
X Error: BadValue (integer parameter out of range for operation) 2
  Extension:    152 (Uknown extension)
  Minor opcode: 3 (Unknown request)
  Resource id:  0x0
X Error: BadValue (integer parameter out of range for operation) 2
  Extension:    152 (Uknown extension)
  Minor opcode: 3 (Unknown request)
  Resource id:  0x0
X Error: BadValue (integer parameter out of range for operation) 2
  Extension:    152 (Uknown extension)
  Minor opcode: 3 (Unknown request)
  Resource id:  0x0
X Error: BadValue (integer parameter out of range for operation) 2
  Extension:    152 (Uknown extension)
  Minor opcode: 3 (Unknown request)
  Resource id:  0x0
QGLContext::makeCurrent(): Cannot make invalid context current.
QGLContext::makeCurrent(): Cannot make invalid context current.
X Error: BadValue (integer parameter out of range for operation) 2
  Extension:    152 (Uknown extension)
  Minor opcode: 3 (Unknown request)
  Resource id:  0x0
X Error: BadValue (integer parameter out of range for operation) 2
  Extension:    152 (Uknown extension)
  Minor opcode: 3 (Unknown request)
  Resource id:  0x0
X Error: BadValue (integer parameter out of range for operation) 2
  Extension:    152 (Uknown extension)
  Minor opcode: 3 (Unknown request)
  Resource id:  0x0
X Error: BadValue (integer parameter out of range for operation) 2
  Extension:    152 (Uknown extension)
  Minor opcode: 3 (Unknown request)
  Resource id:  0x0
X Error: BadValue (integer parameter out of range for operation) 2
  Extension:    152 (Uknown extension)
  Minor opcode: 3 (Unknown request)
  Resource id:  0x0
X Error: BadValue (integer parameter out of range for operation) 2
  Extension:    152 (Uknown extension)
  Minor opcode: 3 (Unknown request)
  Resource id:  0x0
X Error: BadValue (integer parameter out of range for operation) 2
  Extension:    152 (Uknown extension)
  Minor opcode: 3 (Unknown request)
  Resource id:  0x0
X Error: BadValue (integer parameter out of range for operation) 2
  Extension:    152 (Uknown extension)
  Minor opcode: 3 (Unknown request)
  Resource id:  0x0
QGLContext::makeCurrent(): Cannot make invalid context current.
X Error: BadValue (integer parameter out of range for operation) 2
  Extension:    152 (Uknown extension)
  Minor opcode: 3 (Unknown request)
  Resource id:  0x0
QGLTempContext: Unable to create GL context.
X Error: GLXBadFBConfig 167
  Extension:    152 (Uknown extension)
  Minor opcode: 34 (Unknown request)
  Resource id:  0x426
X Error: BadValue (integer parameter out of range for operation) 2
  Extension:    152 (Uknown extension)
  Minor opcode: 3 (Unknown request)
  Resource id:  0x0
QGLContext::makeCurrent(): Cannot make invalid context current.
X Error: BadValue (integer parameter out of range for operation) 2
  Extension:    152 (Uknown extension)
  Minor opcode: 3 (Unknown request)
  Resource id:  0x0
QGLTempContext: Unable to create GL context.
X Error: BadValue (integer parameter out of range for operation) 2
  Extension:    152 (Uknown extension)
  Minor opcode: 3 (Unknown request)
  Resource id:  0x0
QGLTempContext: Unable to create GL context.
```

Then when opening a NETCDF-CF file it closes up with the following message:

`VAssert(dims.size() >= 1 && dims.size() <=2) failed in DataMgr.cpp, line 3575
`
I have already checked my file for CF compliance and it passes,

Thanks for your help,

**Comment by clyne** [comment]
Is there any way that you can provide a copy of your data set, preferably something of minimal size that demonstrates the problem?


> On Oct 2, 2019, at 4:16 PM, manuelvalera <notifications@github.com> wrote:
> 
> Hi,
> 
> I am trying to run in CentOS, the program starts up and opens with the following messages:
> 
> X Error: BadValue (integer parameter out of range for operation) 2
>   Extension:    152 (Uknown extension)
>   Minor opcode: 3 (Unknown request)
>   Resource id:  0x0
> X Error: BadValue (integer parameter out of range for operation) 2
>   Extension:    152 (Uknown extension)
>   Minor opcode: 3 (Unknown request)
>   Resource id:  0x0
> X Error: BadValue (integer parameter out of range for operation) 2
>   Extension:    152 (Uknown extension)
>   Minor opcode: 3 (Unknown request)
>   Resource id:  0x0
> X Error: BadValue (integer parameter out of range for operation) 2
>   Extension:    152 (Uknown extension)
>   Minor opcode: 3 (Unknown request)
>   Resource id:  0x0
> X Error: BadValue (integer parameter out of range for operation) 2
>   Extension:    152 (Uknown extension)
>   Minor opcode: 3 (Unknown request)
>   Resource id:  0x0
> X Error: BadValue (integer parameter out of range for operation) 2
>   Extension:    152 (Uknown extension)
>   Minor opcode: 3 (Unknown request)
>   Resource id:  0x0
> QGLContext::makeCurrent(): Cannot make invalid context current.
> QGLContext::makeCurrent(): Cannot make invalid context current.
> X Error: BadValue (integer parameter out of range for operation) 2
>   Extension:    152 (Uknown extension)
>   Minor opcode: 3 (Unknown request)
>   Resource id:  0x0
> X Error: BadValue (integer parameter out of range for operation) 2
>   Extension:    152 (Uknown extension)
>   Minor opcode: 3 (Unknown request)
>   Resource id:  0x0
> X Error: BadValue (integer parameter out of range for operation) 2
>   Extension:    152 (Uknown extension)
>   Minor opcode: 3 (Unknown request)
>   Resource id:  0x0
> X Error: BadValue (integer parameter out of range for operation) 2
>   Extension:    152 (Uknown extension)
>   Minor opcode: 3 (Unknown request)
>   Resource id:  0x0
> X Error: BadValue (integer parameter out of range for operation) 2
>   Extension:    152 (Uknown extension)
>   Minor opcode: 3 (Unknown request)
>   Resource id:  0x0
> X Error: BadValue (integer parameter out of range for operation) 2
>   Extension:    152 (Uknown extension)
>   Minor opcode: 3 (Unknown request)
>   Resource id:  0x0
> X Error: BadValue (integer parameter out of range for operation) 2
>   Extension:    152 (Uknown extension)
>   Minor opcode: 3 (Unknown request)
>   Resource id:  0x0
> X Error: BadValue (integer parameter out of range for operation) 2
>   Extension:    152 (Uknown extension)
>   Minor opcode: 3 (Unknown request)
>   Resource id:  0x0
> QGLContext::makeCurrent(): Cannot make invalid context current.
> X Error: BadValue (integer parameter out of range for operation) 2
>   Extension:    152 (Uknown extension)
>   Minor opcode: 3 (Unknown request)
>   Resource id:  0x0
> QGLTempContext: Unable to create GL context.
> X Error: GLXBadFBConfig 167
>   Extension:    152 (Uknown extension)
>   Minor opcode: 34 (Unknown request)
>   Resource id:  0x426
> X Error: BadValue (integer parameter out of range for operation) 2
>   Extension:    152 (Uknown extension)
>   Minor opcode: 3 (Unknown request)
>   Resource id:  0x0
> QGLContext::makeCurrent(): Cannot make invalid context current.
> X Error: BadValue (integer parameter out of range for operation) 2
>   Extension:    152 (Uknown extension)
>   Minor opcode: 3 (Unknown request)
>   Resource id:  0x0
> QGLTempContext: Unable to create GL context.
> X Error: BadValue (integer parameter out of range for operation) 2
>   Extension:    152 (Uknown extension)
>   Minor opcode: 3 (Unknown request)
>   Resource id:  0x0
> QGLTempContext: Unable to create GL context.
> 
> Then when opening a NETCDF-CF file it closes up with the following message:
> 
> VAssert(dims.size() >= 1 && dims.size() <=2) failed in DataMgr.cpp, line 3575 
> I have already checked my file for CF compliance and it passes,
> 
> Thanks for your help,
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

John Clyne
National Center for Atmospheric Research
303.497.1236 (w), 303.809.1922 (c)
clyne@ucar.edu

**Comment by manuelvalera** [comment]
Hi, thanks for the reply,

I can provide the dataset in a google drive link if that works:

https://drive.google.com/open?id=1bR7_10-i51eqSrvQgBb_j9lEK1MhAniw

Best,

Manuel

**Comment by clyne** [comment]
Thanks. We’ll look at it soon.

cheers- jc


> On Oct 3, 2019, at 12:22 PM, manuelvalera <notifications@github.com> wrote:
> 
> Hi, thanks for the reply,
> 
> I can provide the dataset in a google drive link if that works:
> 
> https://drive.google.com/open?id=1bR7_10-i51eqSrvQgBb_j9lEK1MhAniw
> 
> Best,
> 
> Manuel
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

John Clyne
National Center for Atmospheric Research
303.497.1236 (w), 303.809.1922 (c)
clyne@ucar.edu

**Comment by clyne** [comment]
This data set  contains a 3D curvilinear grid. I.e. all three of the grid coordinate variables (lon, lat, lev) are functions of all three logical (mesh) coordinates, i-j-k. For example, 'lon' is a function of nx, ny, and nz. At this time vapor only supports "layered" curvilinear grids: the horizontal coordinates, such as lat and lon, may be functions of both two logical coordinates (i,j), but the horizontal coordinates can not be dependent on k. 

A couple of things to note:

1. Even though vapor does not support this grid type the application should not crash. A bug report has been opened: https://github.com/NCAR/VAPOR/issues/1862

2. Even though the coordinate variables are defined as 3D they appear to be constant over some of the axis, and it may be possible to redefine them as 2D coordinates.
