### ISSUE TITLE
Help with Vapor 3 project

### ISSUE THREAD

**Issue by jvalan** [NCAR/VAPOR-SupportPage#9]
So I am working modelling hurricane data in Vapor 3. My end goal is to create an automated system which will take my data, input it all into Vapor 3, run through preset camera angles and render out a 3d looping animation of the hurricane moving in less than 15 minutes.

Currently I'm just starting up this project and would like to know if there are any tutorials on how to get the program to run an animation for version 3, as opposed to the version 2 tutorials I've found. I have been importing netcdf files, but they appear to be just static images. How can I combine and animate these files with Vapor 3?

**Comment by sgpearse** [comment]
> So I am working modelling hurricane data in Vapor 3. My end goal is to create an automated system which will take my data, input it all into Vapor 3, run through preset camera angles and render out a 3d looping animation of the hurricane moving in less than 15 minutes.

Unfortunately this is not supported yet.  Vapor needs a user to control and capture frames.  But this feature is on our radar and will be implemented in a future release, but I can't yet say when.

>Currently I'm just starting up this project and would like to know if there are any tutorials on how to get the program to run an animation for version 3, as opposed to the version 2 tutorials I've found. I have been importing netcdf files, but they appear to be just static images. How can I combine and animate these files with Vapor 3?

The process is similar to that of Vapor2.  However the menu option to capture the images is worded differently.  Select the following menu items: 

Capture->Image Sequence->PNG

Vapor will then begin recording images every time something changes in your rendering.  Now press the play button in the top of the application, and your time series will begin.

Let me know if anything there didn't make sense.

**Comment by jvalan** [comment]
In regards to animating, all of my netcdf files are single images. How do I import and render multiple netcdf file images into the animation? It seems that every time I add a new dataset, it overwrites the previous ones. How do I cycle through the dataset images so I can record the images changing?

**Comment by jvalan** [comment]
Scratch that, I add a new dataset, and any new renderers use the first dataset I imported and I cannot change the dataset the renderer is using. How do I change datasets?

**Comment by jvalan** [comment]
And the transfer function to load presets doesn't seem to load anything when I select a saved tf file. Am I doing something incorrectly or is there more to it?

**Comment by sgpearse** [comment]
I'm unclear by what you mean when you say that your netCDF files contain an image.  If you could elaborate on this it may help.

To play a set of files that define your simulation in time, then you need to load all fo them at the same time.  If your netCDF files are already CF compliant, then you can click on the _File->Import->NetCDF-CF_ menu, and then select all files that pertain to your simulation.  Then the files will play using the time controls at the top of the application.

**Comment by jvalan** [comment]
I mean that each file is static, so in order to create an animation, I would have to manually load in 20 files one at a time and then cycle through them one by one. I have been importing the files through the method described by you, however, it only seems to import one file and not multiple, even when I select multiple I only seem to get one imported.

So to make an animated sequence, do I manually create 20 different volume renderers? Does the play button cycle through them then? What am I doing wrong?

**Comment by jvalan** [comment]
![Screenshot from 2019-10-04 14-40-49](https://user-images.githubusercontent.com/56135291/66217560-13606980-e6b7-11e9-9405-4ea758908b2c.png)

**Comment by sgpearse** [comment]
It sounds like you may not have a time dimension then.  Can you share a couple of your files?

**Comment by jvalan** [comment]
I am getting all of my files from here: https://nomads.ncep.noaa.gov/pub/data/nccf/com/hur/.
These links expire rapidly, as the data is constantly being updated and discarded, so only the parent directory will work in the future. > prod > hwrf.(a long number, either is fine) > any of the .grb2 files.

I then run the .grb2 files through a converter that turns them into .nc files, which can be read.

**Comment by jvalan** [comment]
I mass downloaded and mass converted 20 of them, so instead of a time dimension, I have a bunch of files. Do you know of anyway I can combine these files together to create a time dimension?

**Comment by sgpearse** [comment]
I use a tool called NCO (the "NetCDF Operators") to do stuff like this.  There are lots of examples online.  Here's a link on how to use it to add a new dimension.  Adding a time dimension might need some extra massaging of the data - but I'm not sure.  Look for responses from a guy named Charlie Zender, who wrote and maintains the package.

https://stackoverflow.com/questions/34536742/define-a-new-dimension-to-one-of-the-variables-in-netcdf-file

We do plan on supporting GRIB in the future, so you won't have to deal with this kind of thing forever.

**Comment by jvalan** [comment]
I'll give it a shot.

**Comment by jvalan** [comment]
The NCO package isn't working for me, are there any other tools out there that can combine the files?

**Comment by sgpearse** [comment]
It's hard to say without knowing the command you tried.

[This thread](https://stackoverflow.com/questions/23957350/netcdf-time-dimension-missing-cdo) seems to do what you're looking for. It's a different link than the first one I gave you. The user 'Ales' has a command that adds a time dimension to a file. The user 'N1B4' has another command that is similar, but also relevant to what you/re trying to do.

I believe something like this will do the job:

ncecat -u time A.nc B.nc C.nc concatenatedFile.nc

**Comment by jvalan** [comment]
Thank you. The NCO package I downloaded didn't contain the ncap2 command, but it did contain ncecat. It seems to work so far and I feel like I'm on the right track now, as I am able to concatenate the files, however when I load it into vapor, I get this message:

Error performing paint event
Failed to read variable "" at time step (0), and
refinement level (-1) and level-of-detail (0)
Invalid variable reference : 

I think there's just something missing from the command.

**Comment by jvalan** [comment]
Is there a way to save and import opacity settings, or at least manually type in the xy variables for the opacity slider points.

I'm referring to this green line in the appearance tab. I want to adjust it and have it all be consistent across multiple files.

![Screenshot from 2019-10-15 17-54-05](https://user-images.githubusercontent.com/56135291/66857671-489e6e80-ef77-11e9-836d-059d7c8322ed.png)

**Comment by jvalan** [comment]
Is there a way to save and import opacity settings, or at least manually type in the xy variables for the opacity slider points.

I'm referring to this green line in the appearance tab. I want to adjust it and have it all be consistent across multiple files.

![Screenshot from 2019-10-15 17-54-05](https://user-images.githubusercontent.com/56135291/66857671-489e6e80-ef77-11e9-836d-059d7c8322ed.png)
